/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spark_example_jni_CudaWrapper */

#ifndef _Included_com_spark_example_jni_CudaWrapper
#define _Included_com_spark_example_jni_CudaWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spark_example_jni_CudaWrapper
 * Method:    CUDAProxy_matrixMul
 * Signature: ([I[I[III)I
 */
JNIEXPORT jint JNICALL Java_com_spark_example_jni_CudaWrapper_CUDAProxy_1matrixMul
  (JNIEnv *, jobject, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_spark_example_jni_CudaWrapper
 * Method:    CUDAProxy_printHello
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_spark_example_jni_CudaWrapper_CUDAProxy_1printHello
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
