/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_CudaWrapper */

#ifndef _Included_jni_CudaWrapper
#define _Included_jni_CudaWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_CudaWrapper
 * Method:    CUDAProxy_matrixAdd
 * Signature: ([F[F[F)I
 */
JNIEXPORT jint JNICALL Java_jni_CudaWrapper_CUDAProxy_1matrixAdd
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
