/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_CudaWrapper */

#ifndef _Included_com_example_jni_CudaWrapper
#define _Included_com_example_jni_CudaWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_CudaWrapper
 * Method:    CUDAProxy_stringMatch
 * Signature: ([BLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_CudaWrapper_CUDAProxy_1stringMatch
  (JNIEnv *, jobject, jbyteArray, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
