/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jni_CudaWrapper */

#ifndef _Included_com_example_jni_CudaWrapper
#define _Included_com_example_jni_CudaWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jni_CudaWrapper
 * Method:    CUDAProxy_matrixMul
 * Signature: ([F[F[FII)I
 */
JNIEXPORT jint JNICALL Java_com_example_jni_CudaWrapper_CUDAProxy_1matrixMul
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
